// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmpaybdlwtfobvryacgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtcGF5YmRsd3Rmb2J2cnlhY2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyOTU0MzIsImV4cCI6MjA4Njg3MTQzMn0.DtMeB2leKAA0IKx7mDEYoO8ig2Bld4gbFzS2w0kV6is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});